"""
Evaluation / monitoring of triangulations generated by the model.

This module turns the raw ``.npy`` outputs that a (possibly multi-rank,
multi-epoch) generation run dumps to disk into summary statistics: how many of
the generated triangulations are geometrically valid (via check_valid) and how
many are genuine FRSTs / FSTs / RSTs / STs (via check_FRST, using CYTools).

Layering:
  - ``monitor_perf`` is the core scorer for one batch of (polytope,
    triangulations) and combines both checks, also flagging any triangulation
    that CYTools calls FRST yet the geometric check rejects (a consistency
    alarm).
  - ``parallel_monitor_perf`` shards that work across CPU processes.
  - The ``evaluate_*`` / ``load_*`` / ``find_*`` helpers locate, merge and feed
    the per-rank/per-epoch output files into the scorer and persist results.
"""

from cytransformer.validation.check_valid import compute_volume, check_valid_triangulation
from cytransformer.validation.check_frst import FRST_check
from cytransformer.utilities import tokens_triang_to_vert_indices_woo_triang, vert_indices_triang_to_vert_coord_triang, vert_coord_woo_triang_to_vert_coord_wo_triang, save_output
import numpy as np
import time
from typing import Tuple
import os
import sys
import math
import shutil
import multiprocessing

from concurrent.futures import ThreadPoolExecutor

import json



def evaluate_generation_results_saved_outputs_to_share_format(save_results_file: str, world_size: int, subset_of_polytopes: int | None = None, subset_of_triangs: int | None = None):
    """
    Load one set of generation outputs (polys/masks shared across ranks, per-rank
    triangulation files concatenated along the triangulation axis), optionally
    restrict to a subset, score them with parallel_monitor_perf and print the
    summary counts.
    """
    polys_masks = np.load(save_results_file+ "_poly_masks_monitoring.npy")
    polys = np.load(save_results_file+ "_polys_monitoring.npy")

    triangs = []
    for i in range(world_size):
        triangs.append(np.load(f"{save_results_file}_rank_{i}_toSave_Ts_new.npy"))

    triangs = np.concatenate(triangs, axis=1)

    print(f"Shapes of loaded arrays: polys_masks: {polys_masks.shape}, polys: {polys.shape}, triangs: {triangs.shape}")
    assert polys.shape[0] == polys_masks.shape[0] == triangs.shape[0], "Inconsistent number of polytopes/triangulations/poly_masks"
    polys = polys[:subset_of_polytopes]
    polys_masks = polys_masks[:subset_of_polytopes]
    triangs = triangs[:subset_of_polytopes, :subset_of_triangs]
    results = parallel_monitor_perf(polys, polys_masks, triangs)
    # Drop the bulky per-triangulation boolean matrix before printing the summary.
    printable_results = {k: v for k, v in results.items() if k != "FRST_indices"}
    print("Results:", printable_results)



def evaluate_generation_results_saved_outputs_format(save_results_folder: str, epoch:int, world_size: int, subset_of_polytopes: int = 40, subset_of_triangs: int = 40):
    """
    Variant of the loader for the per-epoch output layout: gather each rank's
    polys/masks/triangs for a given epoch, concatenate them along the polytope
    axis, optionally subset, score and print the summary counts.
    """
    triangs = []
    polys = []
    polys_masks = []
    for rank in range(world_size):
        triangs.append(np.load(save_results_folder + f"/rank_{rank}-{epoch}_toSave_Ts_new.npy"))
        polys.append(np.load(save_results_folder + f"/rank_{rank}-{epoch}_polys_monitoring.npy"))
        polys_masks.append(np.load(save_results_folder + f"/rank_{rank}-{epoch}_poly_masks_monitoring.npy"))

    triangs = np.concatenate(triangs, axis=0)
    polys = np.concatenate(polys, axis=0)
    polys_masks = np.concatenate(polys_masks, axis=0)

    print(polys_masks.shape)
    print(polys.shape)
    print(triangs.shape)
    polys = polys[:subset_of_polytopes]
    polys_masks = polys_masks[:subset_of_polytopes]
    triangs = triangs[:subset_of_polytopes, :subset_of_triangs]
    results = parallel_monitor_perf(polys, polys_masks, triangs)
    printable_results = {k: v for k, v in results.items() if k != "FRST_indices"}
    print("Results:", printable_results)




def load_and_merge_output_for_given_epoch(save_path: str, epoch: int, ranks: list) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Load the chunks saved in the output directory associated to a given epoch and merge them across ranks, returns them
    The chunks are saved in files named "rank_{rank}-{epoch}_toSave_Ts_new.npy", "rank_{rank}-{epoch}_polys_monitoring.npy" and "rank_{rank}-{epoch}_poly_masks_monitoring.npy"
    """
    merged_polys = []
    merged_polys_masks = []
    merged_Ts = []
    for rank in ranks:
        polys = np.load(f"{save_path}/global_rank_{rank}-{epoch}_polys_monitoring.npy")
        polys_masks = np.load(f"{save_path}/global_rank_{rank}-{epoch}_poly_masks_monitoring.npy")
        Ts = np.load(f"{save_path}/global_rank_{rank}-{epoch}_toSave_Ts_new.npy")
        merged_polys.append(polys)
        merged_polys_masks.append(polys_masks)
        merged_Ts.append(Ts)
    merged_polys = np.concatenate(merged_polys, axis=0)
    merged_polys_masks = np.concatenate(merged_polys_masks, axis=0)
    merged_Ts = np.concatenate(merged_Ts, axis=0)
    return merged_polys, merged_polys_masks, merged_Ts

def find_ranks(save_path: str) -> list:
    """
    Find the ranks in the output directory
    The chunks are saved in files named "rank_{rank}-{epoch}_toSave_Ts_new.npy", "rank_{rank}-{epoch}_polys_monitoring.npy" and "rank_{rank}-{epoch}_poly_masks_monitoring.npy"
    """
    files = os.listdir(save_path)
    ranks = set()
    for file in files:
        if file.startswith("global_rank_") and file.endswith("_toSave_Ts_new.npy"):
            rank = int(file.split("_")[2].split("-")[0])
            ranks.add(rank)
    return list(ranks)

def find_epochs(save_path: str) -> list:
    """
    Find the epochs in the output directory
    The chunks are saved in files named "rank_{rank}-{epoch}_toSave_Ts_new.npy", "rank_{rank}-{epoch}_polys_monitoring.npy" and "rank_{rank}-{epoch}_poly_masks_monitoring.npy"
    """
    files = os.listdir(save_path)
    epochs = set()
    for file in files:
        if file.startswith("global_rank_") and file.endswith("_toSave_Ts_new.npy"):
            epoch = int(file.split("-")[1].split("_")[0])
            epochs.add(epoch)
    return list(epochs)

def evaluate_output_run(save_path:str, result_file_name:str):
    """
    Evaluate the output of the experiment
    Saves the result in a file named result_file_name
    If result_file_name already exists, only the new results are appended
    Args:
        save_path: path to the output directory
        result_file_name: name of the file to save the results
    """
    print(f"Evaluating output in {save_path}")
    ranks = find_ranks(save_path)
    epochs = find_epochs(save_path)
    print(f"Found {len(ranks)} ranks and {len(epochs)} epochs")
    existing_epochs = set()
    if os.path.exists(save_path+"/"+result_file_name):
        print(f"File {result_file_name} already exists, appending new results")
        with open(save_path+"/"+result_file_name, "r") as f:
            lines = f.readlines()
            for line in lines:
                if len(line.strip())>0:
                    results = json.loads(line)
                    existing_epochs.add(int(results["epoch"]))
    else:
        print(f"File {result_file_name} does not exist, creating new file")
        with open(save_path+"/"+result_file_name, "w") as f:
            pass
    epochs = sorted(list(set(epochs) - existing_epochs))
    if len(epochs) == 0:
        print(f"No new epochs to evaluate, exiting")
        return None
    else:
        print("Epochs to process: ", epochs)
        for epoch in epochs:
            print(f"Evaluating epoch {epoch}")
            merged_polys, merged_polys_masks, merged_Ts = load_and_merge_output_for_given_epoch(save_path, epoch, ranks)
            results = parallel_monitor_perf(merged_polys, merged_polys_masks, merged_Ts)
            results["epoch"] = epoch
            printable_results = {k: int(v) for k, v in results.items() if k != "FRST_indices"}
            with open(save_path+"/"+result_file_name, "a") as f:
                f.write(json.dumps(printable_results) + '\n')
            print(printable_results)
        print(f"Results saved in {save_path}/{result_file_name}")
        return results

def collect_results_from_saved_folder_and_save_in_new_folder(experiment_output_save_path:str, experiment_logs_save_path:str) -> None:
    """
    Collect the results corresponding to each run in the experiment_output_save_path and save them in a new folder in the experiment_logs_save_path folder
    The new folder is created in the experiment_logs_save_path folder
    """
    print(f"Collecting results from {experiment_output_save_path} and saving them in {os.path.join(experiment_logs_save_path,'results')}")
    new_results_path = os.path.join(experiment_logs_save_path,"results")
    if not os.path.exists(new_results_path):
        os.makedirs(new_results_path)
    if not os.path.exists(experiment_output_save_path):
        print(f"Saved outputs path {experiment_output_save_path} does not exist")
        return
    # find the name of all the folders in the experiment_output_save_path folder
    runs = os.listdir(experiment_output_save_path)
    # for each folder, collect the results and save them in the experiment_logs_save_path folder
    for run in runs:
        run_path = os.path.join(experiment_output_save_path, run)
        for sampling_mode in ["uniform", "proportional"]:
            for permutation_mode in ["perm_once", "perm_each"]:
                sub_run_path = os.path.join(run_path, sampling_mode+"_"+permutation_mode)
                if os.path.isdir(sub_run_path):
                    # find the name of all the files in the folder
                    files = os.listdir(sub_run_path)
                    # for each file, collect the results and save them in the experiment_logs_save_path folder
                    for file in files:
                        if file.endswith(".out"):
                            file_path = os.path.join(sub_run_path, file)
                            # simply copy the file to the experiment_logs_save_path folder
                            new_file_path = os.path.join(new_results_path, run+"_"+sampling_mode+"_"+permutation_mode+".out")
                            shutil.copy(file_path, new_file_path)
                            print(f"File copied from {file_path} to {new_file_path}")

    print("All results collected and saved in ", new_results_path)


def evaluate_output_experiment(experiment_output_save_path:str, experiment_logs_save_path:str) -> None:
    """
    Evaluate the output of all the runs of an experiment in the experiment_output_save_path folder
    Saves the results corresponding to each run in the corresponding saved_output folder
    Also saves all the results in a new folder in the experiment_logs_save_path folder
    """
    print(f"Evaluating output in {experiment_output_save_path}, saving them in {os.path.join(experiment_logs_save_path,'results')}")
    if not os.path.exists(experiment_output_save_path):
        print(f"Saved outputs path {experiment_output_save_path} does not exist")
        return
    # find the name of all the folders in the experiment_output_save_path folder
    folders = os.listdir(experiment_output_save_path)
    for folder in folders:
        folder_path = os.path.join(experiment_output_save_path, folder)
        if os.path.isdir(folder_path):
            for sampling_mode in ["uniform", "proportional"]:
                for permutation_mode in ["perm_once", "perm_each"]:
                    subfolder_path = os.path.join(folder_path, sampling_mode+"_"+permutation_mode)
                    if os.path.isdir(subfolder_path):
                        evaluate_output_run(subfolder_path, f"{sampling_mode}_{permutation_mode}_results.out")
        # collect more frequently to have intermediate results
        collect_results_from_saved_folder_and_save_in_new_folder(experiment_output_save_path, experiment_logs_save_path)



def monitor_perf(polys, polys_masks, triangs, verbose = True):
    """
    Args:
        polys should be a numpy array of shape (N, #vertices -1 , 4)
        polys_masks should be a numpy array of shape (N, #vertices -1)
        triangs should be a numpy array of shape (N, M, T) (where T = 35 is an upper bound on the number of simplices) (tokens_triang)
    Returns:
        The total number of valid triangulations
        The total number of UNIQUE FRST triangulations and UNIQUE FST triangulations
        Prints an alert if there is a "FRST triangulation" that is not valid
        Returns the triangulations that are not valid but were diagnosed as FRST (and the associated polytopes)
        TODO: The number of FRST triangulations that belong to the database (among all FRST triangulations)
    """



    N, M, _ = triangs.shape
    N2, N_vertices, _ = polys.shape
    assert N == N2

    # Vocabulary/padding index implied by the vertex count (must match training).
    padding_idx = math.comb(N_vertices, 4) + 1 + 1
    if N_vertices not in [9, 10, 11, 12, 13, 14, 15, 20]:
        print("Invalid number of vertices")
        return
    # First pass: geometric validity of every triangulation. For each one, decode
    # tokens -> vertex indices -> vertex coordinates, then check it tiles the
    # polytope (whose volume is computed directly from its vertices).
    valid_triangulations_indices = np.zeros((N,M), dtype = bool)
    start_time = time.time()
    for index_poly in range(N):
        for index_triang in range(M):
            # a list of simplices encoded
            triang = triangs[index_poly, index_triang, :]
            vert_indices_woo_triang = tokens_triang_to_vert_indices_woo_triang(triang, N_vertices)
            vert_coord_woo_triang = vert_indices_triang_to_vert_coord_triang(polys[index_poly,:,:], vert_indices_woo_triang)
            vert_coord_wo_triang = vert_coord_woo_triang_to_vert_coord_wo_triang(vert_coord_woo_triang, dimension = 4)
            if check_valid_triangulation(vert_coord_wo_triang, compute_volume(polys[index_poly,:,:])):
                valid_triangulations_indices[index_poly, index_triang] = True
    if verbose:
        print(f"Validity of triangulations checked for all polytopes - Time elapsed: {np.round((time.time()-start_time)/60, decimals=2)} mn")
        print("Now checking the number of ST, FST and FRST triangulations")

    valid_count = int(np.sum(valid_triangulations_indices))
    # Second pass: classify triangulations via CYTools (ST / FST / RST / FRST).
    non_unique_FRSTs_count, FRST_count, FST_count, RST_count, ST_count, FRST_triangulations_indices = FRST_check(polys, polys_masks, triangs, padding_idx, False, verbose = False)
    non_unique_FRSTs_count = sum(non_unique_FRSTs_count)
    FRST_count = sum(FRST_count)
    FST_count = sum(FST_count)
    RST_count = sum(RST_count)
    ST_count = sum(ST_count)


    # list of tuple (poly, triang) where poly is an array of shape (N_vertices - 1, 4) and triang is an array of shape (T)
    # (note: the same poly can come up several times)
    polys_and_triangs_FRST_but_not_valid = []
    # Cross-check the two methods: anything CYTools calls FRST should also pass the
    # geometric validity test; collect (and warn about) any that do not.
    suspicious_indices = FRST_triangulations_indices & ~valid_triangulations_indices
    for i in range(N):
        for j in range(M):
            if suspicious_indices[i,j]:
                polys_and_triangs_FRST_but_not_valid.append((polys[i,:,:], triangs[i,j,:]))

    if np.sum(FRST_triangulations_indices & ~valid_triangulations_indices) != 0:
        print("There is a supposedly FRST triangulation that is not valid")
    assert isinstance(valid_count, int) and isinstance(FRST_count, int) and isinstance(FST_count, int) and isinstance(RST_count, int) and isinstance(ST_count, int), "Counts should be integers"
    return {"non_unique_FRSTs_count": non_unique_FRSTs_count, "FRST_count": FRST_count, "FST_count": FST_count, "RST_count": RST_count, "ST_count": ST_count, "valid_count": valid_count, "FRST_indices": FRST_triangulations_indices}


def parallel_monitor_perf(polys, polys_masks, triangs):
    """
    Multiprocessing wrapper around monitor_perf: split the polytopes into M-sized
    contiguous chunks (one per worker process), score each chunk in parallel, then
    merge the per-chunk results (summing the counts, concatenating FRST_indices).
    Only rank 0 runs verbosely to avoid interleaved logging.
    """
    num_cpus = multiprocessing.cpu_count()
    print(f"Number of CPUs: {num_cpus}")
    N, M_0, _ = triangs.shape
    N2, N_vertices, _ = polys.shape
    assert N == N2
    # Choose the chunk size M so the N polytopes spread across the available CPUs.
    if N < num_cpus:
        num_processes = N
        M = 1
    else:
        num_processes = num_cpus
        M = (N // num_cpus) + 1

    with multiprocessing.Pool(processes=num_processes) as pool:
        arg_list = [(polys[rank*M:(rank+1)*M, :, :], polys_masks[rank*M:(rank+1)*M, :], triangs[rank*M:(rank+1)*M, :, :], rank == 0) for rank in range(num_processes)]
        results = pool.starmap(monitor_perf, arg_list)


    # merge results from various ranks
    keys = results[0].keys()
    merged_results = {}
    for key in keys:
        if key == "FRST_indices":
            merged_results['FRST_indices'] = np.concatenate([result["FRST_indices"] for result in results], axis=0)
            assert merged_results['FRST_indices'].shape == (N, M_0), f"FRST_indices shape mismatch: expected {(N, M_0)}, got {merged_results['FRST_indices'].shape}"
        else:
            merged_results[key] = sum([result[key] for result in results])

    return merged_results



if __name__ == "__main__":
    experiment_output_save_path = sys.argv[1]
    experiment_logs_save_path = sys.argv[2]

    evaluate_output_experiment(experiment_output_save_path, experiment_logs_save_path)

